baseURL = "http://ericfrommelt.com/"
languageCode = "en-us"
title = "Eric Frommelt"
copyright = "2011 - 2018 Eric Frommelt"
canonifyurls = true
[taxonomies]
  tag = "tags"
  category = "category"
  work = "work"
